// <auto-generated />
namespace RAHSys.Infra.Dados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Adicionadodropcascadeparaasentidadescontratocontratoenderecoeendereco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adicionadodropcascadeparaasentidadescontratocontratoenderecoeendereco));
        
        string IMigrationMetadata.Id
        {
            get { return "201808092230075_Adicionado drop cascade para as entidades contrato, contratoendereco e endereco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
